### ISSUE TITLE
横竖屏切换

### ISSUE THREAD

**Issue by dhcai** [Junhua102/AutoScalingLayout#1]
楼主有没有遇到过从竖屏切换到横屏的时候 布局变小了太多太多

**Comment by Junhua102** [comment]
如果设计的是竖屏，适配到横屏的话，无论怎么适配效果都不会很好。现在的做法是保持纵横比，所以会缩小，一般情况下限定activity方向就行。当然如果你确实想这么做，把designWidth和designHeight设成相等就行，这样横竖屏效果就一样了。
